### PR TITLE
removed dependency to processing, added maven pom

### PR DESCRIPTION
**Pull request by fkleedorfer**
I made minimal changes to avoid dependency creep (processing), and I added a pom as I would like to use this with maven. Somewhere down the line it would be great to publish this library as a maven artifact so integration with maven projects becomes easier.

### CODE REVIEW

**Comment by fkleedorfer** [comment]
Btw, I used some hints in this blog post: http://goto.project-a.com/eliza-slack-integration/
kudos @flobr

**Comment by flobr** [comment]
"Oh great! I will try it when the pull request is merged!"

**Comment by codeanticode** [comment]
@fkleedorfer Many thanks for the contribution, but unfortunately I cannot merge it into the main branch since it breaks the project as a Processing library. When I build it using the ant script included in resources, the library package gets compiled (although Processing examples would need to be updated since now the constructor does not accept the PApplet argument) but running the examples from the PDE give a null error (the default script file cannot be located with the new resource loading code). 

Could not just use [Processing Core](https://mvnrepository.com/artifact/org.processing/core) as its dependency, instead of  Commons IO, so it would still work as Processing lib, but also available through Maven?

**Comment by fkleedorfer** [comment]
I am not sure I understand your suggestion. 

The eliza code is quite useful on its own, but I don't want to introduce the processing dependency into my project just to be able to use the eliza implementation. 

Would it not be better to move the code for integrating it into processing into a different project?

**Pull request merged**
